---
- hosts: localhost
  vars_files:
    - vars.yml  
  tasks:
    - name: Check if port is listening
      wait_for:
        port: "{{ item.name }}"
        delay: 5
        timeout: 10
        msg: "Timeout waiting for {{ item.name }} to respond"
      register: port_check
      ignore_errors: yes
      with_items: "{{ check_port }}"

    - name: Gathering service facts
      service_facts:
      register: services_state

    - name: print all of service status
      debug: var=services_state.ansible_facts.services

    - name: loop for get detail of service
      debug:   
        msg: "{{ item.name }} is not in status {{ item.status }}" 
      failed_when:  item.name not in services or services[item.name].state != item.status
      vars:
        services: "{{ services_state.ansible_facts.services }}"
      ignore_errors: true
      with_items: "{{ service_list }}"
    
